### ISSUE TITLE
Unable to publish one of the packages

### ISSUE THREAD

**Issue by unional** [changesets/changesets#1003]
## Affected Packages

`@mocktomata/nodejs`

```sh
🦋  success packages published successfully:
🦋  @mocktomata/cli@7.0.0-beta.13
🦋  @mocktomata/framework@7.0.0-beta.13
🦋  @mocktomata/io-remote@7.0.0-beta.13
🦋  mocktomata@7.0.0-beta.13
🦋  @mocktomata/service@7.0.0-beta.13
🦋  Creating git tags...
🦋  New tag:  @mocktomata/cli@7.0.0-beta.13
🦋  New tag:  @mocktomata/framework@7.0.0-beta.13
🦋  New tag:  @mocktomata/io-remote@7.0.0-beta.13
🦋  New tag:  mocktomata@7.0.0-beta.13
🦋  New tag:  @mocktomata/service@7.0.0-beta.13
🦋  error packages failed to publish:
🦋  @mocktomata/nodejs@7.0.0-beta.13
 ELIFECYCLE  Command failed with exit code 1.
Error: The process '/home/runner/setup-pnpm/node_modules/.bin/pnpm' failed with exit code 1
    at m._setResult (/home/runner/work/_actions/changesets/action/v1/dist/index.js:102:7258)
    at m.CheckComplete (/home/runner/work/_actions/changesets/action/v1/dist/index.js:102:6686)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/changesets/action/v1/dist/index.js:102:5723)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Error: The process '/home/runner/setup-pnpm/node_modules/.bin/pnpm' failed with exit code 1
```

https://github.com/mocktomata/mocktomata/actions/runs/3390000429/jobs/5633714323

I get the same error when running it locally:

```sh
🦋  warn @mocktomata/cli is not being published because version 7.0.0-beta.13 is already published on npm
🦋  warn @mocktomata/framework is not being published because version 7.0.0-beta.13 is already published on npm
🦋  warn @mocktomata/io-remote is not being published because version 7.0.0-beta.13 is already published on npm
🦋  warn mocktomata is not being published because version 7.0.0-beta.13 is already published on npm
🦋  info @mocktomata/nodejs is being published because our local version (7.0.0-beta.13) has not been published on npm
🦋  info @mocktomata/nodejs is being published to latest rather than beta because there has not been a regular release of it yet
🦋  warn @mocktomata/service is not being published because version 7.0.0-beta.13 is already published on npm
🦋  info Publishing "@mocktomata/nodejs" at "7.0.0-beta.13"
🦋  error 
🦋  error packages failed to publish:
🦋  @mocktomata/nodejs@7.0.0-beta.13
```

However, if I publish it using npm, it goes through:

```sh
pm notice === Tarball Details ===
npm notice name:          @mocktomata/nodejs
npm notice version:       7.0.0-beta.13
npm notice filename:      @mocktomata/nodejs-7.0.0-beta.13.tgz
npm notice package size:  17.5 kB
npm notice unpacked size: 82.7 kB
npm notice shasum:        c7b689567ad4f60df9ec754e9119e73955ab8ce5
npm notice integrity:     sha512-oTYUlhKZscwjb[...]m/IgQ5x3dfEPg==
npm notice total files:   184
npm notice
npm notice Publishing to https://registry.npmjs.org/
npm notice Open https://www.npmjs.com/login/1c8ae675-6b8e-4c3e-ac40-3ce7f1eaab4f to use your security key for authentication or enter OTP from your authenticator app
This operation requires a one-time password.
Enter OTP: 927872
+ @mocktomata/nodejs@7.0.0-beta.13
```

Maybe it's a bug related to its name?

I encounter the same error last time and originally I thought it might relate to access scope issue, but it is not, as this time the previous version already exist (under beta, no latest. Maybe related to that?)

**Comment by unional** [comment]
This is happening every time for the package. Any news?

**Comment by unional** [comment]
I just get out of beta and the issue persist. Still do not know why this is happening.

**Comment by Andarist** [comment]
It's really hard to tell what might be wrong based on the provided description. We'd have to dig further into this, get some additional logs etc.

**Comment by unional** [comment]
How do I get additional log locally? I can try to gather some log in the next release.

**Comment by unional** [comment]
Hi, I need to publish a new version and still getting the same error.

**Comment by ivanbanov** [comment]
same error, changesets swallows the error :(

**Comment by unional** [comment]
I debug in and found that it uses:

`pnpm publish --json --access public --tag latest --no-git-checks`

Upon further debugging by running `pnpm publish` directly on the package,
the failure is caused by some of the workspace dependencies are test projects and I didn't add the `version` field in their package.json.

`pnpm publish --json` does not report the error to `changesets`.
