### ISSUE TITLE
Integration with Rush: how to use with no root package.json file?

### ISSUE THREAD

**Issue by elliot-nelson** [changesets/changesets#1025]
## Problem

In a [Rush](https://rushjs.io) monorepo, there is no root `package.json` (it's generally forbidden and/or discouraged), and instead all of the paths for your individual projects are stored in a root `rush.json` file.

I'm not sure exactly what package or tool is looking for the root package:

```console
❯ changeset
🦋  error NoPkgJsonFound [Error]: No package.json could be found upwards from the directory /Users/enelson/dev/rushstack2
🦋  error     at _callee4$ (/Users/enelson/.nvm/versions/node/v16.15.0/lib/node_modules/@changesets/cli/node_modules/@manypkg/find-root/dist/find-root.cjs.dev.js:217:19)
🦋  error     at tryCatch (/Users/enelson/.nvm/versions/node/v16.15.0/lib/node_modules/@changesets/cli/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
🦋  error     at Generator.<anonymous> (/Users/enelson/.nvm/versions/node/v16.15.0/lib/node_modules/@changesets/cli/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
🦋  error     at Generator.next (/Users/enelson/.nvm/versions/node/v16.15.0/lib/node_modules/@changesets/cli/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
🦋  error     at asyncGeneratorStep (/Users/enelson/.nvm/versions/node/v16.15.0/lib/node_modules/@changesets/cli/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
🦋  error     at _next (/Users/enelson/.nvm/versions/node/v16.15.0/lib/node_modules/@changesets/cli/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9) {
🦋  error   directory: '/Users/enelson/dev/rushstack2'
🦋  error }
```

## Proposed solution

I think first off, if I could get it to the point where at least it is not erroring, maybe I would be able to add a changeset if I explicitly told it what package it was? But ideally, I could add code to get the package list from `rush.json` `projects: []` field, and pass that into changeset to inform it of the projects in the repo.

**Comment by elliot-nelson** [comment]
Ah ok, I see it: https://github.com/Thinkmill/manypkg/tree/master/packages/get-packages

So if we add Rush to the supported monorepo tools here, it should start working "for free" in changesets.

**Comment by Andarist** [comment]
Adding support for this - especially since you are using `.json` for your config file~, should be reasonably accessible. We also control the `@manypkg` scope, so if you happen to prepare a PR there we should be able to release it (and upgrade it here) swiftly.

Out of curiosity - how does pnpm work with Rush? Shouldn't you configure workspaces for it somehow too? I was expected their config to be picked up for you.

**Comment by elliot-nelson** [comment]
Yes, we use pnpm workspaces -- what Rush does is call pnpm with a specific (generally much stricter) pile of command-line options, and it generates a temporary `package.json` on-the-fly in `common/temp` and uses it as the context.

So there's a bit of a disconnect, because when Rush calls pnpm:

 - The root of the monorepo (/) is where we'd keep the .changesets folder
 - But there is no package.json file there
 - The package.json only exists while Rush is running, and usually at `common/temp/package.json`

**Comment by Andarist** [comment]
Ok, roger that 👍 luckily, it seems that we can easily find your config and read the available package globs from it. IIRC `@manypkg/get-packages` also return a `.tool` but since you are so coupled with pnpm I think that:
- we can either return `rush` from there and just invoke `pnpm` (if needed) over `npm` within Changesets based on that
- or map that to `pnpm`

I'd probably go with first, since this way we don't lose information and we might want to do something else based on `.tool === 'rush'` in the future.

**Comment by elliot-nelson** [comment]
OK, make sense! I tried to do a quick local hack-up of `get-packages` to return the package.jsons in my local monorepo, but I still end up with some errors:

```
$ node ~/dev/changesets/packages/cli/bin.js
🦋  error TypeError: Cannot read properties of undefined (reading 'name')
🦋  error     at getDependencyGraph (/Users/enelson/dev/changesets/packages/get-dependents-graph/src/get-dependency-graph.ts:56:32)
🦋  error     at getDependentsGraph (/Users/enelson/dev/changesets/packages/get-dependents-graph/src/index.ts:16:39)
🦋  error     at parse (/Users/enelson/dev/changesets/packages/config/src/index.ts:208:74)
🦋  error     at read (/Users/enelson/dev/changesets/packages/config/src/index.ts:91:10)
🦋  error     at run (/Users/enelson/dev/changesets/packages/cli/src/run.ts:55:14)
```

(So I think there might be some other small edge cases where Rush is not behaving as expected)

**Comment by Andarist** [comment]
The type that you have to return from `get-packages` is this:
```ts
export declare type Packages = {
    tool: Tool;
    packages: Package[];
    root: Package;
};
```

So it seems likely that you need to "fake" the `root` here - it has to contain `.packageJson`. I think that it's likely that you end up with a crash here:
https://github.com/changesets/changesets/blob/e02a0c4b7ec869d21b10495138d9fb193b213917/packages/get-dependents-graph/src/get-dependency-graph.ts#L67

**Comment by elliot-nelson** [comment]
Bingo! It works. I'll play with it and put up a PR this weekend possibly.

**Comment by bluwy** [comment]
I believe this is fixed in https://github.com/changesets/changesets/pull/1655 via https://github.com/changesets/changesets/pull/1069#issuecomment-3544705506, which wil be released in the next major (v3)
