### ISSUE TITLE
Error running with npx

### ISSUE THREAD

**Issue by CHarnel** [changesets/changesets#1048]
## Affected Packages

Not sure which package the `npx changeset` is executing...

## Problem

Hi, I forked a public repo, made changes and submitted a PR. The changeset-bot asked to add a changeset, so I followed the instructions. However when trying to run `npx changeset` it fails with the following error: `npm ERR! could not determine executable to run`. 
A few things I made sure of, before opening an issue here:
- other npx commands work fine
- tried to `npm i -D changeset` before running
- deleted node_modules and re-installed
- googled the problem ofc

The PR can be found [here](https://github.com/hoangvvo/gitflow-workflow-action/pull/25).

<details>
  <summary>Full npm log:</summary>

  ```
  0 verbose cli /Users/.../.nvm/versions/node/v16.16.0/bin/node /Users/.../.nvm/versions/node/v16.16.0/lib/node_modules/npm/bin/npm-cli.js
  1 info using npm@8.11.0
  2 info using node@v16.16.0
  3 timing npm:load:whichnode Completed in 1ms
  4 timing config:load:defaults Completed in 0ms
  5 timing config:load:file:/Users/.../.nvm/versions/node/v16.16.0/lib/node_modules/npm/npmrc Completed in 1ms
  6 timing config:load:builtin Completed in 1ms
  7 timing config:load:cli Completed in 0ms
  8 timing config:load:env Completed in 1ms
  9 timing config:load:file:/Users/.../projects/gitflow-workflow-action/.npmrc Completed in 0ms
  10 timing config:load:project Completed in 1ms
  11 timing config:load:file:/Users/.../.npmrc Completed in 0ms
  12 timing config:load:user Completed in 0ms
  13 timing config:load:file:/Users/.../.nvm/versions/node/v16.16.0/etc/npmrc Completed in 0ms
  14 timing config:load:global Completed in 0ms
  15 timing config:load:validate Completed in 0ms
  16 timing config:load:credentials Completed in 1ms
  17 timing config:load:setEnvs Completed in 0ms
  18 timing config:load Completed in 4ms
  19 timing npm:load:configload Completed in 4ms
  20 timing npm:load:mkdirpcache Completed in 2ms
  21 timing npm:load:mkdirplogs Completed in 0ms
  22 verbose title npm exec changeset
  23 verbose argv "exec" "--" "changeset"
  24 timing npm:load:setTitle Completed in 5ms
  25 timing config:load:flatten Completed in 2ms
  26 timing npm:load:display Completed in 2ms
  27 verbose logfile logs-max:10 dir:/Users/.../.npm/_logs
  28 verbose logfile /Users/.../.npm/_logs/2022-12-25T08_10_31_818Z-debug-0.log
  29 timing npm:load:logFile Completed in 2ms
  30 timing npm:load:timers Completed in 0ms
  31 timing npm:load:configScope Completed in 0ms
  32 timing npm:load Completed in 17ms
  33 silly logfile start cleaning logs, removing 1 files
  34 silly logfile done cleaning log files
  35 timing arborist:ctor Completed in 1ms
  36 timing arborist:ctor Completed in 0ms
  37 timing command:exec Completed in 47ms
  38 verbose stack Error: could not determine executable to run
  38 verbose stack     at getBinFromManifest (/Users/.../.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
  38 verbose stack     at exec (/Users/.../.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:135:15)
  38 verbose stack     at async module.exports (/Users/.../.nvm/versions/node/v16.16.0/lib/node_modules/npm/lib/cli.js:78:5)
  39 verbose pkgid changeset@0.2.6
  40 verbose cwd /Users/.../projects/gitflow-workflow-action
  41 verbose Darwin 21.3.0
  42 verbose node v16.16.0
  43 verbose npm  v8.11.0
  44 error could not determine executable to run
  45 verbose exit 1
  46 timing npm Completed in 98ms
  47 verbose code 1
  48 error A complete log of this run can be found in:
  48 error     /Users/.../.npm/_logs/2022-12-25T08_10_31_818Z-debug-0.log
  
  ```
</details>

**Comment by saiumesh535** [comment]
I had a similar issue and missed installing the CLI. try installing cli and try again 

`npm install @changesets/cli`

and try 

`npx changeset init`

**Comment by Netail** [comment]
Seems like it tries to fetch https://registry.npmjs.org/changeset, which is https://github.com/eugeneware/changeset

**Comment by bluwy** [comment]
Related to https://github.com/changesets/changesets/issues/1426, you should use `npx @changesets/cli` instead, but that also has unrelated errors currently unfortunately.

**Comment by Maliksb11** [comment]
ok

**Comment by Netail** [comment]
I think the documentation where `npx` is used should be updated with `@changesets/cli` instead of `changeset` to prevent confusing. `npx changeset` only works when you've installed the package already, else it tries to fetch the other one

**Comment by bluwy** [comment]
We've updated the docs: https://github.com/changesets/changesets/pull/1515
