### ISSUE TITLE
Node 18 "Failed to find where HEAD diverged from origin/master"

### ISSUE THREAD

**Issue by ivanbanov** [changesets/changesets#1055]
We use changeset on CI to check the bump plan. It was working as expected on Node 14.
After upgrading to Node 18 the script fails with the following error
```
Failed to find where HEAD diverged from origin/master. Does origin/master exist?
```

While debugging it seems like everything is working as expected from the git side, but somehow the status fails internally
```
npx changeset status --since=origin/master
```

The logs from the debug
```
git merge-base master HEAD
6344833a5c76c7b5982061c82a7b064dc971510f

git merge-base origin/master HEAD
6344833a5c76c7b5982061c82a7b064dc971510f

git branch -r
  origin/master
  origin/mds-000-fix-changeset

git branch
  master
* mds-000-fix-changeset

@changeset/git getDivergedCommit()
6344833a5c76c7b5982061c82a7b064dc971510f

status
  stdout: '',
  stderr: '🦋  \x1B[31merror\x1B[39m Error: Failed to find where HEAD diverged from origin/master. Does origin/master exist?\n' +
    '🦋  \x1B[31merror\x1B[39m     at getDivergedCommit (/var/lib/bamboo-home/local-working-dir/2719746/RTB-DEST391-JOB1/node_modules/.pnpm/@changesets+git@2.0.0/node_modules/@changesets/git/dist/git.cjs.dev.js:66:11)\n' +
    '🦋  \x1B[31merror\x1B[39m     at async Object.getChangedChangesetFilesSinceRef (/var/lib/bamboo-home/local-working-dir/2719746/RTB-DEST391-JOB1/node_modules/.pnpm/@changesets+git@2.0.0/node_modules/@changesets/git/dist/git.cjs.dev.js:221:24)\n' +
    '🦋  \x1B[31merror\x1B[39m     at async filterChangesetsSinceRef (/var/lib/bamboo-home/local-working-dir/2719746/RTB-DEST391-JOB1/node_modules/.pnpm/@changesets+read@0.5.9/node_modules/@changesets/read/dist/read.cjs.dev.js:107:25)\n' +
    '🦋  \x1B[31merror\x1B[39m     at async Object.getChangesets [as default] (/var/lib/bamboo-home/local-working-dir/2719746/RTB-DEST391-JOB1/node_modules/.pnpm/@changesets+read@0.5.9/node_modules/@changesets/read/dist/read.cjs.dev.js:130:16)\n' +
    '🦋  \x1B[31merror\x1B[39m     at async Object.getReleasePlan [as default] (/var/lib/bamboo-home/local-working-dir/2719746/RTB-DEST391-JOB1/node_modules/.pnpm/@changesets+get-release-plan@3.0.16/node_modules/@changesets/get-release-plan/dist/get-release-plan.cjs.dev.js:70:22)\n' +
    '🦋  \x1B[31merror\x1B[39m     at async getStatus (/var/lib/bamboo-home/local-working-dir/2719746/RTB-DEST391-JOB1/node_modules/.pnpm/@changesets+cli@2.26.0/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1165:23)\n' +
    '🦋  \x1B[31merror\x1B[39m     at async run$2 (/var/lib/bamboo-home/local-working-dir/2719746/RTB-DEST391-JOB1/node_modules/.pnpm/@changesets+cli@2.26.0/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1446:11)\n',
```

Im scratching my head trying to figure out what could possibly be wrong, any clue?

**Comment by williamlmao** [comment]
I've got the same issue when trying to publish from the turborepo design system repo https://vercel.com/templates/react/turborepo-design-system

```
🦋  error Error: Failed to find where HEAD diverged from master. Does master exist?
🦋  error     at getDivergedCommit (/Users/wl/personalprojects/turborepo-design-system/node_modules/@changesets/git/dist/git.cjs.dev.js:66:11)
🦋  error     at async getChangedFilesSince (/Users/wl/personalprojects/turborepo-design-system/node_modules/@changesets/git/dist/git.cjs.dev.js:198:22)
🦋  error     at async Object.getChangedPackagesSinceRef (/Users/wl/personalprojects/turborepo-design-system/node_modules/@changesets/git/dist/git.cjs.dev.js:239:24)
🦋  error     at async add (/Users/wl/personalprojects/turborepo-design-system/node_modules/@changesets/cli/dist/cli.cjs.dev.js:527:29)
🦋  error     at async run$2 (/Users/wl/personalprojects/turborepo-design-system/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1330:5)
```

**Comment by Andarist** [comment]
@ivanbanov can you check what `cwd` is used by Changesets [here](https://github.com/changesets/changesets/blob/521205dc8c70fe71b181bd3c4bb7c9c6d2e721d2/packages/git/src/index.ts#L49)?

@williamlmao most likely you can fix this by using this value in your `.changeset/config.json`:
```json
{
  "baseBranch": "main"
}
```

**Comment by ivanbanov** [comment]
@Andarist I just got the logs

```
Node 14 process.cwd()
/var/lib/bamboo-home/local-working-dir/2719746/RTB-DEST391-JOB1

Node 18 process.cwd()
/var/lib/bamboo-home/local-working-dir/131073/RTB-DEST391-JOB1
```

Note, it works properly on my Mac with Node18

**Comment by ivanbanov** [comment]
I thought I should also add my changeset config here, just in case

`.changeset/config.json`
```json
{
  "$schema": "https://unpkg.com/@changesets/config@1.6.3/schema.json",
  "changelog": "@changesets/cli/changelog",
  "commit": false,
  "linked": [],
  "access": "restricted",
  "baseBranch": "origin/master",
  "ignore": [],
  "updateInternalDependencies": "patch",
  "___experimentalUnsafeOptions_WILL_CHANGE_IN_PATCH": {
    "updateInternalDependents": "always"
  },
  "snapshot": { "useCalculatedVersion": true }
}
```

**Comment by coreybruyere** [comment]
@williamlmao where are you changing your branch to master. I've cloned turbo-repo-designsystem and am having the same issue.

**Comment by sscaff1** [comment]
Locally this ran fine for me. In a gitlab pipeline, this was failing to run. Changing baseBranch to "origin/main" resolved my issue (previously it was "main").

**Comment by ben-laird** [comment]
This is failing for me in CI where I check if a PR has a changeset in it. I've tried pretty much all the solutions provided in this issue, like changing the `baseBranch` property to "main" or "origin/main" to changing it in the command running in ci. My default "master branch" whenever I make a new git repository locally is "main", so I haven't tried changing the name of any branches because there's no need to for my use case. Is there something I'm not seeing?

`.github/workflows/pr.yml`:

```yaml
name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install

      - name: Check if PR has Changeset
        run: pnpm changeset status
```

`.changeset/config.json`:

```json
{
  "$schema": "https://unpkg.com/@changesets/config@2.3.0/schema.json",
  "changelog": "@changesets/cli/changelog",
  "baseBranch": "main",
  "commit": false,
  "fixed": [],
  "linked": [],
  "access": "public",
  "updateInternalDependencies": "patch",
  "ignore": [],
  "privatePackages": { "version": true, "tag": true }
}
```

Error/Call Stack (some directories replaced by `<other-folders>` for brevity/security):

```sh
🦋  error Error: Failed to find where HEAD diverged from main. Does main exist?
🦋  error     at getDivergedCommit (/home/runner/work/<other-folders>/node_modules/.pnpm/@changesets+git@2.0.0/node_modules/@changesets/git/dist/git.cjs.dev.js:66:11)
🦋  error     at async getChangedFilesSince (/home/runner/work/<other-folders>/node_modules/.pnpm/@changesets+git@2.0.0/node_modules/@changesets/git/dist/git.cjs.dev.js:198:22)
🦋  error     at async Object.getChangedPackagesSinceRef (/home/runner/work/<other-folders>/node_modules/.pnpm/@changesets+git@2.0.0/node_modules/@changesets/git/dist/git.cjs.dev.js:239:24)
🦋  error     at async getStatus (/home/runner/work/<other-folders>/node_modules/.pnpm/@changesets+cli@2.26.0/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1170:27)
🦋  error     at async run$2 (/home/runner/work/<other-folders>/node_modules/.pnpm/@changesets+cli@2.26.0/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1446:11)
Error: Process completed with exit code 1.
```

**Comment by mckelveygreg** [comment]
Thankfully i don't need to run this in a node 18 environment, but other steps of my code do. So setting my builder for `node-16.18.0` is at least a work around

**Comment by thundermiracle** [comment]
Checkout with `full history` and set baseBranch to `origin/main` will solve this problem. Hope help someone.

In your `ci.yaml`

```yaml
    steps:
      - uses: actions/checkout@v3
        with:
          # check out full history
          fetch-depth: 0

      # set baseBranch to origin/main
      - run: pnpm changeset status --since origin/main
```

**Comment by voronin-ivan** [comment]
In case the options above don't help you, try to use the last published tag:
```
last_tag=$(git describe --tags --abbrev=0)
pnpm changeset status --since $last_tag
```

**Comment by mborysenko** [comment]
I'm getting the same error message when I introduce changes during build job, for example I have overrides that I copy to the main folder during job execution, basically those are uncommitted changes. If I do that locally and commit and push changes to the branch, issue is gone.

**Comment by mborysenko** [comment]
> I'm getting the same error message when I introduce changes during build job, for example I have overrides that I copy to the main folder during job execution, basically those are uncommitted changes. If I do that locally and commit and push changes to the branch, issue is gone.

BTW, job is running on node 16.13.1

**Comment by pablojsx** [comment]
🦋  error Error: Failed to find where HEAD diverged from main. Does main exist?

**Comment by zachstence** [comment]
I ran into this issue because I had cloned a fresh repository where the default branch is `next` (our dev branch) and I had not yet checked out the `main` branch (our production branch, what is used in `.changeset/config.json`). Since I hadn't checked out `main`, it didn't exist locally, and resulted in this error.

Simply running `git checkout main` fixed it.

**Comment by joeldenning** [comment]
Changing the `baseBranch` in `.changeset/config.json` to `origin/branchname` rather than `branchname` worked for me

**Comment by nerdybeast** [comment]
> Checkout with `full history` and set baseBranch to `origin/main` will solve this problem. Hope help someone.
> 
> In your `ci.yaml`
> 
> ```yaml
>     steps:
>       - uses: actions/checkout@v3
>         with:
>           # check out full history
>           fetch-depth: 0
> 
>       # set baseBranch to origin/main
>       - run: pnpm changeset status --since origin/main
> ```

I'm running in Azure Pipelines and this worked for me as well.
My main branch is `master` and I had to set `baseBranch` to `origin/master`

Then in my `azure-pipelines.yml` file I had to override the repo checkout step to pull the full git history:
```
steps:
  - checkout: 'self'
    fetchDepth: 0
```

Successful output 🎉

![image](https://github.com/changesets/changesets/assets/15707802/c2b20bad-d1ba-4275-8ed9-e1ad9cc3cedc)

**Comment by theoephraim** [comment]
It would be nice to not have to fetch the _full_ git history of the repo. Not necessarily a huge problem for most, but not ideal for a larger older project, and any CI speed improvements are always welcome.

I tried adding a `git fetch origin main` step to my workflow after the initial `- uses: actions/checkout@v4` and while that does allow a subsequent step of `git diff origin/main HEAD` to work correctly, I still get the `Failed to find where HEAD diverged from origin/main. Does origin/main exist` error when running `changesets status`

What other info does changesets need?

**Comment by unional** [comment]
I'm getting `Failed to find where HEAD diverged from undefined` and I have set `baseBranch: main`:

```sh
🦋  error Error: Failed to find where HEAD diverged from undefined. Does undefined exist?
🦋  error     at getDivergedCommit (.../node_modules/.pnpm/@changesets+git@3.0.0/node_modules/@changesets/git/dist/changesets-git.cjs.js:66:11)
🦋  error     at async getChangedFilesSince (.../.pnpm/@changesets+git@3.0.0/node_modules/@changesets/git/dist/changesets-git.cjs.js:198:22)
🦋  error     at async Object.getChangedPackagesSinceRef (.../node_modules/.pnpm/@changesets+git@3.0.0/node_modules/@changesets/git/dist/changesets-git.cjs.js:239:24)
🦋  error     at async getVersionableChangedPackages (.../node_modules/.pnpm/@changesets+cli@2.27.2/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:259:27)
🦋  error     at async getStatus (.../node_modules/.pnpm/@changesets+cli@2.27.2/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1159:27)
🦋  error     at async run (.../node_modules/.pnpm/@changesets+cli@2.27.2/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1434:11)
```

This is caused by:

```js
// getStatus()
const sinceBranch = since === undefined ? sinceMaster ? "master" : undefined : since;

  const changedPackages = await getVersionableChangedPackages(config, {
    cwd,
    ref: sinceBranch
  });

// getVersionableChangedPackages()
  const changedPackages = await git.getChangedPackagesSinceRef(_objectSpread({
    ref: config.baseBranch,
    changedFilePatterns: config.changedFilePatterns
  }, options));
```

The `options` has `{ ref: undefined }` thus overrides the `config.baseBranch`

**Comment by matt-gold** [comment]
I was running into this when using `actions/checkout@v3`, updating to `actions/checkout@v4` fixed the issue.

**Comment by ethanneff** [comment]
yeah, I got the CI working with the following:


```yml
name: Require Changeset

on:
  pull_request:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  requireChangeset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          BUILD_TYPE: 'code'

      - name: Require changeset
        run: pnpm changeset status --since=origin/master

```


But I agree with @theoephraim, `fetch-depth: 0` should not be a solution as this punishes very large/old repositories.

**Comment by cefn** [comment]
See also https://github.com/changesets/changesets/issues/1558 if you are hitting this in a Gitlab pipeline.

**Comment by goastler** [comment]
one way to avoid `fetch-depth: 0` is to checkout the base branch then jump back to the current branch like so:
```bash

            # checkout the base and head refs
            # ensures we have history for both
            - name: Checkout base ref
              run: git fetch origin ${{ github.base_ref }} && git checkout ${{ github.base_ref }}

            - name: Checkout head ref
              run: git fetch origin ${{ github.head_ref }} && git checkout ${{ github.head_ref }}

```

this only gets the history for your head and base branch rather than history for all branches. Changesets is working nicely with the above change and `origin/main` as the `baseBranch`
