### ISSUE TITLE
Changesets for the monorepo root workspace

### ISSUE THREAD

**Issue by sarneeh** [changesets/changesets#1137]
## Problem

Currently, I can only handle changes and maintain changelogs for packages/apps that are under a monorepo. The problem is, that there are plenty of things that are mostly related to the monorepo itself - like CI workflows, tooling etc. and it would be great to be able to maintain a changelog for it as well.

## Proposed solution

Perhaps something like `changesets add --root`, or a configuration entry that would make `changesets` also check for changes that are not related to the apps/packages in the monorepo.

**Comment by jmatsushita** [comment]
I am also missing this feature. Another approach would be to list the mono repo when running `changeset add` if the root repo's `package.json` has a `name` field.

**Comment by wmertens** [comment]
I added `- '.'` to my pnpm-workspaces.yaml and made the root have a name + private:true and it versions it as expected. (I added the monorepo name as a fixed package with the main package)

**Comment by ghost91-** [comment]
@wmertens I just tried that solution, and it works fine for changesets, but it seems to break other tools. For example, turborepo doesn't work this way anymore. Imo, a proper solution inside changesets to include the workspace root is needed.

**Comment by GauBen** [comment]
Somewhat related: without Wout's fix, changeset will crash with this error

```
🦋  error TypeError: Cannot read properties of undefined (reading 'packageJson')
🦋  error     at createChangeset (.../dist/changesets-cli.cjs.js:417:75)
🦋  error     at add (.../dist/changesets-cli.cjs.js:514:26)
🦋  error     at async run (.../dist/changesets-cli.cjs.js:1347:5)
```

It happens when all packages but the workspace root are private
