### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'author')

### ISSUE THREAD

**Issue by benmccann** [changesets/changesets#1164]
## Affected Packages

https://github.com/sveltejs/eslint-config

## Problem

I just added changesets to an existing package. Then I pushed a major changeset and got the error below and can't quite figure out what might be causing it:
```
🦋  error TypeError: Cannot read properties of null (reading 'author')
🦋  error     at getInfo (/home/runner/work/eslint-config/eslint-config/node_modules/.pnpm/@changesets+get-github-info@0.5.2/node_modules/@changesets/get-github-info/dist/get-github-info.cjs.dev.js:235:12)
🦋  error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
🦋  error     at async /home/runner/work/eslint-config/eslint-config/node_modules/.pnpm/@svitejs+changesets-changelog-github-compact@1.1.0/node_modules/@svitejs/changesets-changelog-github-compact/dist/index.cjs:91:35
🦋  error     at async Object.getReleaseLine (/home/runner/work/eslint-config/eslint-config/node_modules/.pnpm/@svitejs+changesets-changelog-github-compact@1.1.0/node_modules/@svitejs/changesets-changelog-github-compact/dist/index.cjs:75:19)
🦋  error     at async Promise.all (index 0)
🦋  error     at async generateChangesForVersionTypeMarkdown (/home/runner/work/eslint-config/eslint-config/node_modules/.pnpm/@changesets+apply-release-plan@6.1.3/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:188:22)
🦋  error     at async getChangelogEntry (/home/runner/work/eslint-config/eslint-config/node_modules/.pnpm/@changesets+apply-release-plan@6.1.3/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:[24](https://github.com/sveltejs/eslint-config/actions/runs/5034696739/jobs/9029643173#step:6:25)3:39)
🦋  error     at async /home/runner/work/eslint-config/eslint-config/node_modules/.pnpm/@changesets+apply-release-plan@6.1.3/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:416:21
🦋  error     at async Promise.all (index 0)
🦋  error     at async Object.applyReleasePlan [as default] (/home/runner/work/eslint-config/eslint-config/node_modules/.pnpm/@changesets+apply-release-plan@6.1.3/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:[30](https://github.com/sveltejs/eslint-config/actions/runs/5034696739/jobs/9029643173#step:6:31)7:[31](https://github.com/sveltejs/eslint-config/actions/runs/5034696739/jobs/9029643173#step:6:32))
Error: Error: The process '/usr/local/bin/node' failed with exit code 1
Error: The process '/usr/local/bin/node' failed with exit code 1
```

It seems not to have fetched data from GitHub. However, I see in the logs:
```
GITHUB_TOKEN Permissions
  Contents: write
  Metadata: read
  PullRequests: write
```

This is also what I see in the logs on https://github.com/sveltejs/kit where changesets is working correctly, which makes me think it's not a problem with the `GITHUB_TOKEN`. I haven't done anything to set `GITHUB_TOKEN` but believe it should be set automatically.

I did a force push to drop the last commit containing the major changeset since it failed.

## Proposed solution

Probably I did something wrong setting up changesets or skipped some step or something. However, it'd be nice if there could be some type of validation to catch whatever error I created.

**Comment by benmccann** [comment]
Ah, I see this is a duplicate of https://github.com/changesets/changesets/issues/795 actually, so will close this
