### ISSUE TITLE
Github dataloader may return null, resulting in runtime error.

### ISSUE THREAD

**Issue by Jym77** [changesets/changesets#1174]
## Affected Packages

get-github-info

## Problem

At lines [179-181](https://github.com/changesets/changesets/blob/main/packages/get-github-info/src/index.ts#L179-L181), `getInfo` assumes that the `data` returned by the `GHDataLoader` exists.
I had a case where I made a typo in the organisation name in my config file (my bad), this resulted in the commit not existing and GHDataLoader call returning `null`.
Following that, the existence test of `data.author` crashed with:
> error TypeError: Cannot read properties of null (reading 'author')
🦋  error     at getInfo (/home/runner/work/alfa-integrations/alfa-integrations/node_modules/@changesets/get-github-info/dist/get-github-info.cjs.dev.js:235:[12](https://github.com/Siteimprove/alfa-integrations/actions/runs/5343633235/jobs/9686989832#step:11:13))
🦋  error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
🦋  error     at async /home/runner/work/alfa-integrations/alfa-integrations/scripts/src/changelog.js:62:31
🦋  error     at async Object.getReleaseLine (/home/runner/work/alfa-integrations/alfa-integrations/scripts/src/changelog.js:46:19)
🦋  error     at async Promise.all (index 0)
🦋  error     at async generateChangesForVersionTypeMarkdown (/home/runner/work/alfa-integrations/alfa-integrations/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:188:22)
🦋  error     at async getChangelogEntry (/home/runner/work/alfa-integrations/alfa-integrations/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:243:179)
🦋  error     at async /home/runner/work/alfa-integrations/alfa-integrations/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:4[16](https://github.com/Siteimprove/alfa-integrations/actions/runs/5343633235/jobs/9686989832#step:11:17):21
🦋  error     at async Promise.all (index 0)
🦋  error     at async Object.applyReleasePlan [as default] (/home/runner/work/alfa-integrations/alfa-integrations/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:307:31)

## Proposed solution

Inserting a test after line 179 that `data !== null`, and escaping the function early, should avoid this problem. Looking at the rest of the code, it seems that `getInfo` can return a bunch of `null`, so it could be a could "no data" value.
OTOH, we may want some better error signalling and reporting, and instead throw a ``new Error(`Couldn't find ${commit} on ${repo}`)`` or something like that (similar to the tests made just before). Or some better error handling in GHDataLoader (not sure what are all the possible causes of failures there and they might need specific error reporting).

**Comment by Andarist** [comment]
> Inserting a test after line 179 that data !== null, and escaping the function early, should avoid this problem.

That makes sense. So I guess that no errors are returned in such a case and [this](https://github.com/changesets/changesets/blob/8ede784e5fc3629858a57643fdaab76ffb631520/packages/get-github-info/src/index.ts#L103) isn't enough to cover for failures like this?

> Or some better error handling in GHDataLoader (not sure what are all the possible causes of failures there and they might need specific error reporting).

Yeah, it would be great to have granular error reporting there but it's hard to know all possible ways in which this can fail.

Could you dump the exact query that has been executed here? We could then try to play with it in [the playground](https://docs.github.com/en/graphql/overview/explorer) to get a better feeling of how that API behaves.

**Comment by Jym77** [comment]
> Could you dump the exact query that has been executed here? We could then try to play with it in [the playground](https://docs.github.com/en/graphql/overview/explorer) to get a better feeling of how that API behaves.

Not sure exactly 😅, but I was using the [changesets-changelog-github-compact](https://github.com/svitejs/changesets-changelog-github-compact) reporter ([custom version by me](https://github.com/Siteimprove/alfa-integrations/blob/main/scripts/src/changelog.ts), but not touching that bit), it failed at [this `getInfo` call](https://github.com/Siteimprove/alfa-integrations/blob/main/scripts/src/changelog.ts#L80-L83), which I reconstitute as being this call:
`getInfo({repo: "Siteimprove/alfa", commit: "734130651925db608942b80777e780cd7406bfa9"})`
(the commit does not exist in that repository).

[Action run that failed with that](https://github.com/Siteimprove/alfa-integrations/actions/runs/5343633235/jobs/9686989832)
[Fix that made the next call work](https://github.com/Siteimprove/alfa-integrations/commit/09279e6d8b527ef90b1ba1e7132f26b03a1ec17b) (only fixing the repo name in the config file)

(I'm not fluent enough in GraphQL to play with the playground myself…)

**Comment by JounQin** [comment]
https://github.com/un-ts/json-schema-migrate/actions/runs/14235449968/job/39893844851#step:6:27

I met this issue recently, and it's persisted.
