### ISSUE TITLE
getPackageInfo bug in changeset npm info code

### ISSUE THREAD

**Issue by MartinDawson** [changesets/changesets#1223]
```ts
function getPackageInfo(packageJson) {
  return npmRequestLimit(async () => {
    logger.info(`npm info ${packageJson.name}`); // Due to a couple of issues with yarnpkg, we also want to override the npm registry when doing
    // npm info.
    // Issues: We sometimes get back cached responses, i.e old data about packages which causes
    // `publish` to behave incorrectly. It can also cause issues when publishing private packages
    // as they will always give a 404, which will tell `publish` to always try to publish.
    // See: https://github.com/yarnpkg/yarn/issues/2935#issuecomment-355292633

    let result = await spawn__default['default']("npm", ["info", packageJson.name, "--registry", getCorrectRegistry(packageJson), "--json"]); // Github package registry returns empty string when calling npm info
    // for a non-existent package instead of a E404

    if (result.stdout.toString() === "") {
      return {
        error: {
          code: "E404"
        }
      };
    }

    return jsonParse(result.stdout.toString());
  });
}
```

This assumption doesn't seem to be correct: `// Github package registry returns empty string when calling npm info
    // for a non-existent package instead of a E404`
    
My command for my private github package:

> npm info @sede-x/shell-ds-react-base --registry https://npm.pkg.github.com --json

Results in an empty string. This package DOES exist though.

I have confirmed it exists by doing a GET request with the authToken in the `Bearer {token}` and getting this response:

![Screenshot from 2023-08-25 10-57-21](https://github.com/changesets/changesets/assets/15030491/7653762b-80db-4178-b589-463890141fd8)

Here's the command ran with `--verbose`:

```
npm info @sede-x/shell-ds-react-base --registry https://npm.pkg.github.com --json --verbose
npm verb cli /home/martin/.nvm/versions/node/v18.13.0/bin/node /home/martin/.nvm/versions/node/v18.13.0/bin/npm
npm info using npm@8.19.3
npm info using node@v18.13.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/home/martin/.nvm/versions/node/v18.13.0/lib/node_modules/npm/npmrc Completed in 0ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/home/martin/Documents/shell-ds-react-framework/packages/react-base/.npmrc Completed in 0ms
npm timing config:load:project Completed in 4ms
npm timing config:load:file:/home/martin/.npmrc Completed in 2ms
npm timing config:load:user Completed in 4ms
npm timing config:load:file:/home/martin/.nvm/versions/node/v18.13.0/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 14ms
npm timing npm:load:configload Completed in 14ms
npm timing npm:load:mkdirpcache Completed in 0ms
npm timing npm:load:mkdirplogs Completed in 1ms
npm verb title npm info @sede-x/shell-ds-react-base
npm verb argv "info" "@sede-x/shell-ds-react-base" "--registry" "https://npm.pkg.github.com" "--json" "--loglevel" "verbose"
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 6ms
npm verb logfile logs-max:10 dir:/home/martin/.npm/_logs
npm verb logfile /home/martin/.npm/_logs/2023-08-25T09_51_22_267Z-debug-0.log
npm timing npm:load:logFile Completed in 12ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 35ms
npm http fetch GET 200 https://npm.pkg.github.com/@sede-x%2fshell-ds-react-base 392ms (cache updated)
npm timing command:info Completed in 400ms
npm verb exit 0
npm timing npm Completed in 444ms
npm info ok 
```

Clearly it has a 200 response, not a 404.

Here's the command ran for a package that does NOT exist:

```
npm info @sede-x/shell-ds-react-based --registry https://npm.pkg.github.com --json --verbose
npm verb cli /home/martin/.nvm/versions/node/v18.13.0/bin/node /home/martin/.nvm/versions/node/v18.13.0/bin/npm
npm info using npm@8.19.3
npm info using node@v18.13.0
npm timing npm:load:whichnode Completed in 1ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/home/martin/.nvm/versions/node/v18.13.0/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 3ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/home/martin/Documents/shell-ds-react-framework/packages/react-base/.npmrc Completed in 0ms
npm timing config:load:project Completed in 8ms
npm timing config:load:file:/home/martin/.npmrc Completed in 1ms
npm timing config:load:user Completed in 2ms
npm timing config:load:file:/home/martin/.nvm/versions/node/v18.13.0/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 17ms
npm timing npm:load:configload Completed in 17ms
npm timing npm:load:mkdirpcache Completed in 0ms
npm timing npm:load:mkdirplogs Completed in 0ms
npm verb title npm info @sede-x/shell-ds-react-based
npm verb argv "info" "@sede-x/shell-ds-react-based" "--registry" "https://npm.pkg.github.com" "--json" "--loglevel" "verbose"
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 7ms
npm verb logfile logs-max:10 dir:/home/martin/.npm/_logs
npm verb logfile /home/martin/.npm/_logs/2023-08-25T09_53_19_169Z-debug-0.log
npm timing npm:load:logFile Completed in 5ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 32ms
npm http fetch GET 404 https://npm.pkg.github.com/@sede-x%2fshell-ds-react-based 249ms (cache skip)
npm timing command:info Completed in 257ms
npm verb stack HttpErrorGeneral: 404 Not Found - GET https://npm.pkg.github.com/@sede-x%2fshell-ds-react-based - npm package "shell-ds-react-based" does not exist under owner "sede-x"
npm verb stack     at /home/martin/.nvm/versions/node/v18.13.0/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verb stack     at async RegistryFetcher.packument (/home/martin/.nvm/versions/node/v18.13.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:92:19)
npm verb stack     at async View.getData (/home/martin/.nvm/versions/node/v18.13.0/lib/node_modules/npm/lib/commands/view.js:203:20)
npm verb stack     at async View.exec (/home/martin/.nvm/versions/node/v18.13.0/lib/node_modules/npm/lib/commands/view.js:111:28)
npm verb stack     at async module.exports (/home/martin/.nvm/versions/node/v18.13.0/lib/node_modules/npm/lib/cli.js:78:5)
npm verb statusCode 404
npm verb pkgid @sede-x/shell-ds-react-based@latest
npm verb cwd /home/martin/Documents/shell-ds-react-framework/packages/react-base
npm verb Linux 6.2.0-26-generic
npm verb node v18.13.0
npm verb npm  v8.19.3
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.pkg.github.com/@sede-x%2fshell-ds-react-based - npm package "shell-ds-react-based" does not exist under owner "sede-x"
npm ERR! 404 
npm ERR! 404  '@sede-x/shell-ds-react-based@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
{
  "error": {
    "code": "E404",
    "summary": "Not Found - GET https://npm.pkg.github.com/@sede-x%2fshell-ds-react-based - npm package \"shell-ds-react-based\" does not exist under owner \"sede-x\"",
    "detail": "\n '@sede-x/shell-ds-react-based@latest' is not in this registry.\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}
npm verb exit 1
npm timing npm Completed in 317ms
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martin/.npm/_logs/2023-08-25T09_53_19_169Z-debug-0.log
```

This is giving an expected 404 which is correct.

Our package is hosted on github registry, one of multiple packages attached to the same repository.

This looks like a bug to me in the code and the wrong assumption that github is returning an empty string for 404 packages. Maybe Github has recently changed this behaviour?

Thanks

**Comment by MartinDawson** [comment]
Nevermind, this issue can be closed.

There was some type of caching somewhere. Once I published another version, and then deleted that version, the cache updated and I see 0.0.0 returned now.

Thanks.
