### ISSUE TITLE
Multiple nested workspaces are not recognized

### ISSUE THREAD

**Issue by mandarino-x** [changesets/changesets#1244]
## Affected Packages

"@changesets/cli": "^2.26.2",

## Problem

pnpm-workspace.yaml
```yaml
packages:
  - 'apps/*'
  - 'packages/**/*'
```

The current directory structure is
```
packages/
  - vue/
     - package.json
     - src/
         - test.js
         - package.json
  - react/
     - package.json
     - dist/
         - test.js
         - package.json
     - src/
         - test.js
         - package.json
```

Full error log
```Full error log
🦋  error TypeError: Cannot read properties of undefined (reading 'packageJson')
🦋  error     at createChangeset (D:\codeBase\yhdfe-plugins\node_modules\.pnpm\@changesets+cli@2.26.2\node_modules\@changesets\cli\dist\cli.cjs.dev.js:421:75)
🦋  error     at add (D:\codeBase\yhdfe-plugins\node_modules\.pnpm\@changesets+cli@2.26.2\node_modules\@changesets\cli\dist\cli.cjs.dev.js:535:26)
🦋  error     at async run$2 (D:\codeBase\yhdfe-plugins\node_modules\.pnpm\@changesets+cli@2.26.2\node_modules\@changesets\cli\dist\cli.cjs.dev.js:1334:5)
```

## Proposed solution

Searching the relevant information did not find a solution

**Comment by jaywalker21** [comment]
One of your changeset files must have the package name different from ones in `package.json`.

**Comment by bluwy** [comment]
Please re-open with a proper repro so we can check the issue locally.
