### ISSUE TITLE
TypeError: Invalid comparator: workspace

### ISSUE THREAD

**Issue by js-egton** [changesets/changesets#1247]
## Affected Packages

`changesets/action@v1`

## Problem

We're using the GitHub action to automate our changeset process, and as of today we're starting to see this error in the action log:

```
🦋  error TypeError: Invalid comparator: workspace
🦋  error     at Comparator.parse (/home/runner/work/ui/ui/node_modules/.pnpm/semver@7.5.4/node_modules/semver/classes/comparator.js:39:13)
🦋  error     at new Comparator (/home/runner/work/ui/ui/node_modules/.pnpm/semver@7.5.4/node_modules/semver/classes/comparator.js:23:10)
🦋  error     at /home/runner/work/ui/ui/node_modules/.pnpm/semver@7.5.4/node_modules/semver/classes/range.js:138:47
🦋  error     at Array.map (<anonymous>)
🦋  error     at Range.parseRange (/home/runner/work/ui/ui/node_modules/.pnpm/semver@7.5.4/node_modules/semver/classes/range.js:138:35)
🦋  error     at /home/runner/work/ui/ui/node_modules/.pnpm/semver@7.5.4/node_modules/semver/classes/range.js:41:22
🦋  error     at Array.map (<anonymous>)
🦋  error     at new Range (/home/runner/work/ui/ui/node_modules/.pnpm/semver@7.5.4/node_modules/semver/classes/range.js:41:8)
🦋  error     at versionPackage (/home/runner/work/ui/ui/node_modules/.pnpm/@changesets+apply-release-plan@6.1.4/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:175:9)
🦋  error     at /home/runner/work/ui/ui/node_modules/.pnpm/@changesets+apply-release-plan@6.1.4/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:3[32](https://github.com/emisgroup/ui/actions/runs/6573380752/job/17861235923#step:8:33):12
```

We use `workspace:^` to reference other packages in our monorepo, such as:

`package.json`
```json
"dependencies": {
  "ui-core": "workspace:^"
}
```

and this has been working without issue for us up until this afternoon.

**Comment by js-egton** [comment]
Closing as this issue appears to have resolved itself — the action is working as expected.
