### ISSUE TITLE
Issue while `pnpm changeset`

### ISSUE THREAD

**Issue by wojtekKrol** [changesets/changesets#1397]
## Problem

I'm creating a package and wanted to add changeset to it, I did and once I want to run `pnpm changeset` I got error:

```
Package "zod-to-fields" must depend on the current version of "react": "0.0.0" vs "^18.2.0"
Package "react" must depend on the current version of "react": "0.0.0" vs "^18.2.0"
🦋  error TypeError: Cannot read properties of undefined (reading 'dependents')
🦋  error     at /Users/wojciechkrol/WebstormProjects/my-projects/zod-to-fields/node_modules/.pnpm/@changesets+get-dependents-graph@2.1.0/node_modules/@changesets/get-dependents-graph/dist/changesets-get-dependents-graph.cjs.js:139:38
🦋  error     at Array.forEach (<anonymous>)
🦋  error     at /Users/wojciechkrol/WebstormProjects/my-projects/zod-to-fields/node_modules/.pnpm/@changesets+get-dependents-graph@2.1.0/node_modules/@changesets/get-dependents-graph/dist/changesets-get-dependents-graph.cjs.js:138:20
🦋  error     at Array.forEach (<anonymous>)
🦋  error     at Object.getDependentsGraph (/Users/wojciechkrol/WebstormProjects/my-projects/zod-to-fields/node_modules/.pnpm/@changesets+get-dependents-graph@2.1.0/node_modules/@changesets/get-dependents-graph/dist/changesets-get-dependents-graph.cjs.js:132:21)
🦋  error     at parse (/Users/wojciechkrol/WebstormProjects/my-projects/zod-to-fields/node_modules/.pnpm/@changesets+config@3.0.1/node_modules/@changesets/config/dist/changesets-config.cjs.js:255:50)
🦋  error     at Object.read (/Users/wojciechkrol/WebstormProjects/my-projects/zod-to-fields/node_modules/.pnpm/@changesets+config@3.0.1/node_modules/@changesets/config/dist/changesets-config.cjs.js:138:10)
🦋  error     at async run (/Users/wojciechkrol/WebstormProjects/my-projects/zod-to-fields/node_modules/.pnpm/@changesets+cli@2.27.6/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1279:16)
```

my package is `zod-to-fields`

this is my `package.json`

```
{
  "name": "zod-to-fields",
  "version": "0.1.2",
  "description": "Turn your Zod schemas into configurable field arrays for easy integration with HTML, React, Vue, and more.",
  "main": "lib/cjs/index.js",
  "module": "lib/esm/index.js",
  "author": "Wojciech Król <wojciechkrol97@gmail.com>",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/wojtekKrol/zod-to-fields.git",
    "bugs": "https://github.com/wojtekKrol/zod-to-fields/issues"
  },
  "engines": {
    "node": ">=18"
  },
  "exports": {
    ".": {
      "types": {
        "import": "./lib/esm/index.d.ts",
        "require": "./lib/cjs/index.d.ts"
      },
      "import": "./lib/esm/index.js",
      "default": "./lib/esm/index.js",
      "require": "./lib/cjs/index.js"
    }
  },
  "files": [
    "lib",
    "README.md",
    "LICENSE"
  ],
  "keywords": [
    "dynamic-fields",
    "field-generator",
    "fields",
    "react",
    "schema",
    "svelte",
    "type-safe",
    "typescript",
    "validation",
    "vue",
    "zod"
  ],
  "peerDependencies": {
    "zod": "^3.0.0"
  },
  "scripts": {
    "dev:react": "pnpm --filter react dev",
    "preinstall": "npx only-allow pnpm",
    "prepare": "husky install",
    "build": "tsc --project tsconfig.cjs.json && tsc-alias --project tsconfig.cjs.json && tsc --project tsconfig.esm.json && tsc-alias --project tsconfig.esm.json && echo 'Build complete'",
    "freshBuild": "rimraf lib  && pnpm run build",
    "clean": "rimraf node_modules lib pnpm-lock.yaml",
    "lint": "pnpm lint:code && pnpm lint:text && pnpm lint:types",
    "lint:code": "eslint --cache --cache-location node_modules/.cache/eslint --cache-strategy content --ext ts .",
    "lint:text": "prettier --check \"**/*.{json,md,mdx,yml}\"",
    "lint:types": "pnpm freshBuild",
    "pretest": "pnpm lint",
    "coverage": "jest --coverage",
    "test": "jest",
    "publish:npm": "pnpm publish --access public",
    "publish:github": "pnpm publish --registry=https://npm.pkg.github.com/"
  },
  "devDependencies": {
    "@changesets/cli": "^2.27.6",
    "@types/jest": "29.5.5",
    "@types/react": "^18.2.15",
    "@types/validator": "13.11.5",
    "@typescript-eslint/eslint-plugin": "6.4.1",
    "@typescript-eslint/parser": "6.4.1",
    "eslint": "8.47.0",
    "eslint-config-next": "13.4.19",
    "eslint-config-prettier": "9.0.0",
    "eslint-import-resolver-typescript": "3.6.0",
    "eslint-plugin-import": "2.28.1",
    "eslint-plugin-jest": "27.4.0",
    "eslint-plugin-prettier": "5.0.0",
    "husky": "8.0.3",
    "jest": "29.7.0",
    "jest-environment-jsdom": "29.7.0",
    "jest-ts-webcompat-resolver": "1.0.0",
    "lint-staged": "14.0.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "rimraf": "5.0.1",
    "ts-jest": "29.1.1",
    "ts-node": "10.9.1",
    "tsc-alias": "1.8.8",
    "tsup": "7.2.0",
    "typescript": "5.4.5",
    "zod": "^3.0.0"
  },
  "dependencies": {
    "validator": "13.12.0"
  }
}
```

I don't know why it occured to be honest

**Comment by Andarist** [comment]
I sent you PRs fixing setup of your repository and I'm fixing the crash that you managed to reproduce using that broken configuration here: https://github.com/changesets/changesets/pull/1400 😉

**Comment by wojtekKrol** [comment]
Yes I saw

> I sent you PRs fixing setup of your repository and I'm fixing the crash that you managed to reproduce using that broken configuration here: #1400 😉

Thank you!
