### ISSUE TITLE
Request: add documentation for how to delete a package from a changesets monorepo

### ISSUE THREAD

**Issue by handeyeco** [changesets/changesets#1416]
## Affected Packages

Hello 👋

`@khanacademy/perseus-error`

## Problem

We moved `@khanacademy/perseus-error` into `@khanacademy/perseus-core`: https://github.com/Khan/perseus/pull/1411

We searched for awhile, but didn't see any official documentation on deleting a package from `changesets` and `changesets --help` also didn't provide any clues. We ended up YOLO-ing it even though we got an error:

https://github.com/Khan/perseus/actions/runs/9941814947/job/27461831835

```
$ /home/runner/work/perseus/perseus/node_modules/.bin/changeset status --verbose --output changeset-status.json
🦋  error Error: Could not find package information for @khanacademy/perseus-error
🦋  error     at /home/runner/work/perseus/perseus/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:279:15
🦋  error     at Array.forEach (<anonymous>)
🦋  error     at /home/runner/work/perseus/perseus/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:271:44
🦋  error     at Array.forEach (<anonymous>)
🦋  error     at flattenReleases (/home/runner/work/perseus/perseus/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:266:14)
🦋  error     at Object.assembleReleasePlan [as default] (/home/runner/work/perseus/perseus/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:496:18)
🦋  error     at Object.getReleasePlan [as default] (/home/runner/work/perseus/perseus/node_modules/@changesets/get-release-plan/dist/get-release-plan.cjs.dev.js:71:49)
🦋  error     at async getStatus (/home/runner/work/perseus/perseus/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1080:23)
🦋  error     at async run$2 (/home/runner/work/perseus/perseus/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1355:11)
error Command failed with exit code 1.
```

Now we're getting release errors:

https://github.com/Khan/perseus/actions/runs/9942133564/job/27462868278

```
🦋  error Error: Could not find package information for @khanacademy/perseus-error
🦋  error     at /home/runner/work/perseus/perseus/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:279:15
🦋  error     at Array.forEach (<anonymous>)
🦋  error     at /home/runner/work/perseus/perseus/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:271:44
🦋  error     at Array.forEach (<anonymous>)
🦋  error     at flattenReleases (/home/runner/work/perseus/perseus/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:266:14)
🦋  error     at Object.assembleReleasePlan [as default] (/home/runner/work/perseus/perseus/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:496:18)
🦋  error     at version (/home/runner/work/perseus/perseus/node_modules/@changesets/cli/dist/cli.cjs.dev.js:599:60)
🦋  error     at async run$2 (/home/runner/work/perseus/perseus/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1337:11)
```

## Proposed solution

Any help resolving this issue would be appreciated, but I think ultimately the request is for documentation on how to properly delete a package from `changesets`.

**Comment by bluwy** [comment]
This is documented on the site at https://github.com/changesets/changesets/commit/126988415d795396d93c194ea05da7799f13fabd now
