### ISSUE TITLE
Error thrown after successful major changeset generation/commit.

### ISSUE THREAD

**Issue by ReDrUm** [changesets/changesets#374]
## Affected Packages

`@changesets/cli`'s `enquirer` dependency.

## Problem

An unexpected error _was_ thrown after successfully generating a changeset and having it committed.

I'm unable to reproduce this error (using same package selection, and description). Possibly a race condition?

```
...
🦋  Changeset added and committed
🦋  warn This Changeset includes a major change and we STRONGLY recommend adding more information to the changeset:
🦋  warn WHAT the breaking change is
🦋  warn WHY the change was made
🦋  warn HOW a consumer should update their code
🦋  info /Users/person/workspace/project/.changeset/tough-spiders-retire.md
TypeError: Cannot read property 'enabled' of undefined
    at AutoComplete.toggle (/Users/person/workspace/project/node_modules/@changesets/cli/node_modules/enquirer/lib/types/array.js:230:17)
    at AutoComplete.space (/Users/person/workspace/project/node_modules/@changesets/cli/node_modules/enquirer/lib/types/array.js:202:10)
    at AutoComplete.space (/Users/person/workspace/project/node_modules/@changesets/cli/node_modules/enquirer/lib/prompts/autocomplete.js:30:42)
    at AutoComplete.keypress (/Users/person/workspace/project/node_modules/@changesets/cli/node_modules/enquirer/lib/prompt.js:44:17)
    at ReadStream.on (/Users/person/workspace/project/node_modules/@changesets/cli/node_modules/enquirer/lib/keypress.js:199:26)
    at ReadStream.emit (events.js:205:15)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1145:36)
    at ReadStream.emit (events.js:200:13)
error Command failed with exit code 1.
```

## Proposed solution

None, sorry.

**Comment by RajaBellebon** [comment]
Hello @ReDrUm ,

I tried after removing my `node_modules` and re-running `bolt` and it works fine

```➜  atlassian-frontend git:(AFP-1637-add-multi-entry-points) bolt changeset
⚡️   bolt v0.24.3 (node v12.3.1)
$                            changeset
$ /Users/rbellebon/.config/yarn/global/node_modules/bolt/node_modules/.bin/yarn config get user-agent yarn/1.22.0 npm/? node/v12.3.1 darwin x64
🦋  Which packages would you like to include? · @atlaskit/ci-scripts
🦋  Which packages should have a major bump? · @atlaskit/ci-scripts
🦋  Please enter a summary for this change (this will be in the changelogs)
🦋  Summary · test
🦋  === Releasing the following packages ===
🦋  [Major]
🦋    @atlaskit/ci-scripts
🦋  ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
🦋  ║                                                      ========= NOTE ========                                                       ║
🦋  ║All dependents of these packages that will be incompatible with the new version will be patch bumped when this changeset is applied.║
🦋  ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
🦋  Is this your desired changeset? (Y/n) · true
🦋  Changeset added and committed
🦋  warn This Changeset includes a major change and we STRONGLY recommend adding more information to the changeset:
🦋  warn WHAT the breaking change is
🦋  warn WHY the change was made
🦋  warn HOW a consumer should update their code
🦋  info /Users/rbellebon/atlassian-frontend/.changeset/lazy-cooks-juggle.md
🏁   Done in 27.26s.
➜  atlassian-frontend git:(AFP-1637-add-multi-entry-points)
 ```

Can you try again ?

**Comment by bluwy** [comment]
It might be best reporting this to `enquirer` if possible. Indeed looks like a race condition which is hard to reproduce.
