### ISSUE TITLE
Package filtering error

### ISSUE THREAD

**Issue by ReDrUm** [changesets/changesets#553]
## Affected Packages

@changesets/cli's enquirer dependency.

## Problem

An unexpected error was thrown after typing a word and a space during package selection filtering.

Steps to reproduce:

1. During package selection, type a word to filter packages, but which won't match any packages. e.g. "Foo"
1. Wait for the "No matching choices" label to be displayed.
1. Type a further trailing space. e.g. "Foo ".
1. Observe the error `TypeError: Cannot read property 'enabled' of undefined` is thrown.

```
🦋  Which packages would you like to include? · @af/af-release-dashboard
🦋  Which packages should have a major bump? · No items were selected
🦋  Which packages should have a minor bump? … FooTypeError: Cannot read property 'enabled' of undefined
    at AutoComplete.toggle (/Users/person/workspace/repo/node_modules/enquirer/lib/types/array.js:230:17)
    at AutoComplete.space (/Users/person/workspace/repo/node_modules/enquirer/lib/types/array.js:202:10)
    at AutoComplete.space (/Users/person/workspace/repo/node_modules/enquirer/lib/prompts/autocomplete.js:30:42)
    at AutoComplete.keypress (/Users/person/workspace/repo/node_modules/enquirer/lib/prompt.js:44:23)
    at ReadStream.on (/Users/person/workspace/repo/node_modules/enquirer/lib/keypress.js:205:26)
    at ReadStream.emit (events.js:205:15)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1145:36)
    at ReadStream.emit (events.js:200:13)
error Command failed with exit code 1.
```
> It appears to be the same error as #374

## Proposed solution

Not sure at this stage. I don't have capacity at the moment to investigate the root cause.

**Comment by Andarist** [comment]
I've created a fix for this here: https://github.com/enquirer/enquirer/pull/344

**Comment by jonschlinkert** [comment]
Sorry for the late reply, I'm getting caught up on issues. @doowb or I will review ASAP.

**Comment by Andarist** [comment]
@jonschlinkert no problem - take your time :)
