### ISSUE TITLE
`changeset version` can't be executed using npx

### ISSUE THREAD

**Issue by Andarist** [changesets/changesets#566]
The changelog generator is configured like this:
https://github.com/atlassian/changesets/blob/6353abf925d13c41feb1884124ddb5edc8c33555/.changeset/config.json#L2-L5

This has the unfortunate effect of specifying an **implicit** dependency for the `@changesets/cli` (and `@changesets/apply-release-plan`) which cannot be resolved when running changesets using tools like `npx`. The resolving happens here:
https://github.com/atlassian/changesets/blob/6353abf925d13c41feb1884124ddb5edc8c33555/packages/apply-release-plan/src/index.ts#L209

cc @JakeGinnivan

**Comment by mitchellhamilton** [comment]
I'm not sure I understand, the dependency is resolved from the .changeset directory, why is that wrong? Why wouldn't this work when running through npx?

**Comment by Andarist** [comment]
I haven't tested it myself - got a report about this from @JakeGinnivan - but I believe that the reason behind this is that `npx` is usually used to avoid installing a particular dependency. In this case the probable cause is that no dependencies are installed - Jake has tried to create a GitHub Action which would just run `changeset version` using npx to avoid heavy installs and so on. So whatever dependency was specified in the root `package.json` was simply not installed and thus it has failed to resolve. 

I'm not yet sure how we can accommodate this use case since changelog generators act like plugins~ but the use case sounds very valid to me so I've created this issue to try figuring this out later.

**Comment by JakeGinnivan** [comment]
`npx -p @changesets/cli changeset version` is what I am trying to run.

```
cat .changeset/config.json
{
    "$schema": "https://unpkg.com/@changesets/config@1.5.0/schema.json",
    "changelog": "@changesets/cli/changelog",
    "commit": false,
    "linked": [],
    "access": "public",
    "baseBranch": "main",
    "updateInternalDependencies": "patch",
    "ignore": []
}
```

And I get

`error Error: Cannot find module '@changesets/cli/changelog'`

But it should be installed, for some reason it can't be resolved when running through npx. I haven't had much time to dig into it though

**Comment by JakeGinnivan** [comment]
The motivation is to avoid a full install to just run changesets

**Comment by Andarist** [comment]
> But it should be installed, for some reason it can't be resolved when running through npx. I haven't had much time to dig into it though

It's not installed since... you have not installed `@changesets/cli` locally. Not sure where exactly npx-ed tools are installed but it's surely outside of the cwd. This one could be resolved from within the running changesets (as this changelog generator is installed with it) but the same would happen for other non-relative generators (like the popular `@changesets/changelog-github`)

**Comment by JakeGinnivan** [comment]
That could be solved with `npx -p @changesets/cli -p @changesets/changelog-github changeset version` - which actually might work better. It could be and issue with requiring a path from itself?

**Comment by Andarist** [comment]
Neat! I didn't know that you can use multiple packages like this. Given that it's possible I think this is a suitable solution for the problem - as in: this should be used when you want to use tools like `npx`. There is still a problem in Changesets that doesn't allow for this to execute properly but it can be solved on our end.

I wonder if we should fallback to resolving the generator from the running CLI directory if we fail to resolve it from the cwd which could potentially lead to some edge cases (resolving to a random-ish package/script) or if we should make CLI to accept a `--changelog` options (which has major drawback that passing extra args to the changelog generator would be totally awkward).

Thoughts?

**Comment by JakeGinnivan** [comment]
The above workaround didn't work. I think the structure of how npx installs it is causing problems.

A workaround I have found is

```
npm install --no-package-lock --no-save @changesets/cli
npx changeset version
```

**Comment by Andarist** [comment]
I wonder if this would work when using `@changesets/changelog-github`
```sh
npx changeset version -p @changesets/cli -p @changesets/changelog-github
```

**Comment by cefn** [comment]
I had the same problem and context (needing to run an npm tool without an npm install of the whole monorepo first). it was unfortunate to find that the package rolls its own resolution logic hence breaking in this case. If it helps to establish a way forward, I succeeded at patching the resolve step here by installing `resolve` and `global-dirs` and then replacing... 

```
  let changelogPath = resolveFrom__default["default"](changesetPath, config.changelog[0]);
```

...with...

```
 const path = require('path');
  const globalDirs = require('global-dirs');
  const resolve = require('resolve');
  let changelogPath = path.join(globalDirs.npm.packages, config.changelog[0]);
```

After this patch I got the positive-looking result below. It's not a solution for the long term but could give a basis for resolving within the package itself, maybe?

```
🦋  warn ===============================IMPORTANT!===============================
🦋  warn You are in prerelease mode
🦋  warn If you meant to do a normal release you should revert these changes and run `changeset pre exit`
🦋  warn You can then run `changeset version` again to do a normal release
🦋  warn ----------------------------------------------------------------------
🦋  All files have been updated. Review them and commit at your leisure
```

# Background

Like earlier posters I was trying to rely on a purely global @changesets/cli install. The error presents as... 

```
$ which changeset
/Users/cefn/.nvm/versions/node/v22.0.0/bin/changeset

$ changeset version
🦋  warn ===============================IMPORTANT!===============================
🦋  warn You are in prerelease mode
🦋  warn If you meant to do a normal release you should revert these changes and run `changeset pre exit`
🦋  warn You can then run `changeset version` again to do a normal release
🦋  warn ----------------------------------------------------------------------
🦋  error Error: Cannot find module '@changesets/cli/changelog'
🦋  error Require stack:
🦋  error - /Users/cefn/workspace/gitlab/group/web-core/my-starter/.changeset/noop.js
🦋  error     at Module._resolveFilename (node:internal/modules/cjs/loader:1202:15)
🦋  error     at resolveFileName (/Users/cefn/.nvm/versions/node/v22.0.0/lib/node_modules/@changesets/cli/node_modules/resolve-from/index.js:29:39)
🦋  error     at resolveFrom (/Users/cefn/.nvm/versions/node/v22.0.0/lib/node_modules/@changesets/cli/node_modules/resolve-from/index.js:43:9)
🦋  error     at module.exports [as default] (/Users/cefn/.nvm/versions/node/v22.0.0/lib/node_modules/@changesets/cli/node_modules/resolve-from/index.js:46:47)
🦋  error     at getNewChangelogEntry (/Users/cefn/.nvm/versions/node/v22.0.0/lib/node_modules/@changesets/cli/node_modules/@changesets/apply-release-plan/dist/changesets-apply-release-plan.cjs.js:424:54)
🦋  error     at Object.applyReleasePlan [as default] (/Users/cefn/.nvm/versions/node/v22.0.0/lib/node_modules/@changesets/cli/node_modules/@changesets/apply-release-plan/dist/changesets-apply-release-plan.cjs.js:332:37)
🦋  error     at version (/Users/cefn/.nvm/versions/node/v22.0.0/lib/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1282:69)
🦋  error     at async run (/Users/cefn/.nvm/versions/node/v22.0.0/lib/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1458:11) {
🦋  error   code: 'MODULE_NOT_FOUND',
🦋  error   requireStack: [
🦋  error     '/Users/cefn/workspace/gitlab/group/web-core/my-starter/.changeset/noop.js'
🦋  error   ]
🦋  error }
```

**Comment by cefn** [comment]
Actually wasn't too hard to raise a possible fix PR 

https://github.com/changesets/changesets/pull/1500
