### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'author')

### ISSUE THREAD

**Issue by lockHrt** [changesets/changesets#795]
## Affected Packages
`pkg:@changesets/changelog-github` 

## Problem
`pnpx changeset version` command is giving following error:

```
The following error was encountered while generating changelog entries
We have escaped applying the changesets, and no files should have been affected
🦋  error TypeError: Cannot read properties of null (reading 'author')
🦋  error     at Object.getInfo (project-name\node_modules\.pnpm\@changesets+get-github-info@0.5.0\node_modules\@changesets\get-github-info\dist\get-github-info.cjs.dev.js:228:12)
🦋  error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
🦋  error     at async project-name\node_modules\.pnpm\@changesets+changelog-github@0.4.4\node_modules\@changesets\changelog-github\dist\changelog-github.cjs.dev.js:122:13
🦋  error     at async Object.getReleaseLine (project-name\node_modules\.pnpm\@changesets+changelog-github@0.4.4\node_modules\@changesets\changelog-github\dist\changelog-github.cjs.dev.js:99:19)
🦋  error     at async Promise.all (index 0)
🦋  error     at async generateChangesForVersionTypeMarkdown (project-name\node_modules\.pnpm\@changesets+apply-release-plan@6.0.0\node_modules\@changesets\apply-release-plan\dist\apply-release-plan.cjs.dev.js:188:22)
🦋  error     at async getChangelogEntry (project-name\node_modules\.pnpm\@changesets+apply-release-plan@6.0.0\node_modules\@changesets\apply-release-plan\dist\apply-release-plan.cjs.dev.js:243:109)
🦋  error     at async project-name\node_modules\.pnpm\@changesets+apply-release-plan@6.0.0\node_modules\@changesets\apply-release-plan\dist\apply-release-plan.cjs.dev.js:392:21
🦋  error     at async Promise.all (index 0)
🦋  error     at async Object.applyReleasePlan [as default] (project-name\node_modules\.pnpm\@changesets+apply-release-plan@6.0.0\node_modules\@changesets\apply-release-plan\dist\apply-release-plan.cjs.dev.js:287:31)
 ELIFECYCLE  Command failed with exit code 1.
```

- The `author` field is present in all package.json files.
- `GITHUB_TOKEN` is also set as env variable with Github PAT with both `read:user` and `repo:status` permissions.
- config file: 

>  ```
> {
>   "$schema": "https://unpkg.com/@changesets/config@2.0.0/schema.json",
>   "changelog": ["@changesets/changelog-github", { "repo": "another-dev/project-name" }],
>   "commit": false,
>   "fixed": [],
>   "linked": [],
>   "access": "restricted",
>   "baseBranch": "main",
>   "updateInternalDependencies": "patch",
>   "ignore": []
> }
> ```

- tested `v0.4.4` and `v0.4.3` both giving same error.
- System is windows 10 and node v16.14.2
- `pnpx changeset` is working fine

**Comment by unitario** [comment]
Push your commits to origin.

**Comment by clementcreusat** [comment]
Thanks, same error, @unitario your comment helped ;)

**Comment by dhrjarun** [comment]
Hey @grempe did you find any solution?

**Comment by stormwarning** [comment]
FWIW, just encountered the same error when the changesets action tried to run. Patching get-github-info with some `console.log()`s showed that the data for a particular squash commit was `null` (while data for a subsequent squash was retrieved just fine).

```js
data: {
	a0: {
		a36d415e: null,
		a867d661: {
    		// commitUrl, associatedPullRequests, author values as expected.
		}
	}
}
```

Reverting the offending commit unblocked the workflow and recreating and merging the reverted PR seems to have worked fine. Literally the only difference I can find is that there was an extra space in the initial commit title before the PR number:

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/999825/223226424-96dc73b7-c9b5-4f41-beea-420b8c62c5c3.png">

Not sure if that's a red herring or not, but hopefully this helps someone

**Comment by gr2m** [comment]
I'm running into the same error and none of the suggestions helped. I deleted the whole repository reset the whole git history. The same error still occurs. 

> Patching get-github-info with some `console.log()`s showed that the data for a particular squash commit was `null` (while data for a subsequent squash was retrieved just fine).

@stormwarning How did you add the patches? Did you manage to run the command locally somehow?

**Comment by cseas** [comment]
> `changelog[1].repo` was set to the incorrect repository, which is why the commit could not be found.

Thanks! This was the case for me as well as I copied the config from another project and forgot to update the repo value. The error message is very misleading in identifying this.

**Comment by toakleaf** [comment]
If you're running into this the underlying issue is that the permissions needed are more broad than those [specified here](https://www.npmjs.com/package/@changesets/get-github-info). It says you only need `repo:status` and `read:user`, but I had to broaden the permissions to include everything under `repo` to get it working.

**Comment by kandji-joe** [comment]
> If you're running into this the underlying issue is that the permissions needed are more broad than those [specified here](https://www.npmjs.com/package/@changesets/get-github-info). It says you only need `repo:status` and `read:user`, but I had to broaden the permissions to include everything under `repo` to get it working.

After updating my token to include everything under `repo` it appears to be working now 👍

**Comment by alex-page** [comment]
The error message should be handled differently when the repo in the `config.json` cannot be found. The current error is quite confusing.

**Comment by Seolhun** [comment]
I originally set up my repository to use the GitHub private registry, but recently I switched to npm.
This change affected my changeset command, particularly in the following line from `config.json`:

```json
"changelog": ["@changesets/changelog-github", { "repo": "seolhun/root-editor" }]
```

I deleted this line, It was reolsved.
But, I'm not sure it think this is good solution.

**Comment by MikeHewett** [comment]
> I originally set up my repository to use the GitHub private registry, but recently I switched to npm. This change affected my changeset command, particularly in the following line from `config.json`:
> 
> "changelog": ["@changesets/changelog-github", { "repo": "seolhun/root-editor" }]
> I deleted this line, It was reolsved. But, I'm not sure it is good solution.

@Seolhun I did a similar thing recently and had to remove this plugin. I think its correct in our scenarios as we're not relying on github to generate changelogs but another method.

Your guidance helped me out, cheers.
