### ISSUE TITLE
Cannot read properties of null (reading 'prerelease')

### ISSUE THREAD

**Issue by unional** [changesets/changesets#835]
## Affected Packages

`standard-log`

## Problem

```sh
   yarn cs version
🦋  warn ===============================IMPORTANT!===============================
🦋  warn You are in prerelease mode
🦋  warn If you meant to do a normal release you should revert these changes and run `changeset pre exit`
🦋  warn You can then run `changeset version` again to do a normal release
🦋  warn ----------------------------------------------------------------------
🦋  error TypeError: Cannot read properties of null (reading 'prerelease')
🦋  error     at getPreVersion (D:\code\unional\standard-log\node_modules\@changesets\assemble-release-plan\dist\assemble-release-plan.cjs.dev.js:437:27)
🦋  error     at getPreInfo (D:\code\unional\standard-log\node_modules\@changesets\assemble-release-plan\dist\assemble-release-plan.cjs.dev.js:609:43)
🦋  error     at Object.assembleReleasePlan [as default] (D:\code\unional\standard-log\node_modules\@changesets\assemble-release-plan\dist\assemble-release-plan.cjs.dev.js:490:19)
🦋  error     at version (D:\code\unional\standard-log\node_modules\@changesets\cli\dist\cli.cjs.dev.js:599:60)
🦋  error     at async run$2 (D:\code\unional\standard-log\node_modules\@changesets\cli\dist\cli.cjs.dev.js:1337:11)
```

## Proposed solution

Seems like this is a bug with prerelease.

https://github.com/unional/standard-log/runs/6841190529?check_suite_focus=true

Even after I run `changeset pre exit`, the issue persist. It goes away when I delete the `pre.json` file.

**Comment by Andarist** [comment]
Yeah, it looks like a bug in the prerelease mode. The problem is caused by the fact that `@standard-log/example` is included as part of packages and it's a private package without any `version` and thus parsing `undefined` version return `null` and we crash.

It shouldn't be hard to fix but I think there are some other PRs/issues related to version-less packages so I'd like to look through all of them and fix all at once.

**Comment by wbcs** [comment]
> Yeah, it looks like a bug in the prerelease mode. The problem is caused by the fact that `@standard-log/example` is included as part of packages and it's a private package without any `version` and thus parsing `undefined` version return `null` and we crash.
> 
> It shouldn't be hard to fix but I think there are some other PRs/issues related to version-less packages so I'd like to look through all of them and fix all at once.

Is it fixed?

**Comment by TuiMao233** [comment]
Is there any progress on this issue, I have the same problem

**Comment by vzt7** [comment]
same problem, https://github.com/changesets/changesets/pull/847 It works for me

**Comment by frankxin** [comment]
Hi～ Do we have any update ？We ran into the same issue

**Comment by hmans** [comment]
Also just lost some time to this issue. :( @Andarist, if you give me a pointer as to where to start, I'd have a go at making a PR?

**Comment by ndaba1** [comment]
I just ran into this issue and I can't seem to find a workaround. Does anybody have any hacks that fix this?

**Comment by ndaba1** [comment]
I ended up applying a patch I found from @vzt7's implementation. Find the patch at this [gist](https://gist.github.com/ndaba1/b63f6a30b8f6211a156f835480044d27)

**Comment by AntoineKM** [comment]
Hey, 7 months this pr could help a lot of ppl like all of us can you merge it ?

**Comment by xencodes** [comment]
i ran into the same issue, no fix?

**Comment by airtonix** [comment]
still happening.

**Comment by pngwn** [comment]
I was also having this issue and after some local debugging, it turned out I had a space after one of the versions: `"version": "0.0.5-beta.4 ",` which was causing the parsing of the version to fail. 

There are clearly other reasons why this may happen but thought this might be helpful to someone. The space crept in after resolving some tricky merge conflicts, so flew under the radar.

**Comment by StampixSMO** [comment]
Same here, this was my own mistake. Easiest debugging would be to add run `pnpm changeset version` locally (i.e. to the `getPreVersion` and `getPreInfo` functions and figure out which package is having an unsupported version.

**Comment by equinusocio** [comment]
Got the same issue in 2024.

**Comment by jeddygong** [comment]
@Andarist Excuse me, when will this [PR](https://github.com/MichalBryxi/ember-resources/pull/1) be released?

Every time I enter pre release mode, I have to manually change this file `changesets-assemble-release-plan.cjs.js`

![image](https://github.com/changesets/changesets/assets/64977484/fcf4a9c9-a9e5-4254-b7d9-a023dc0e9e91)

Hope to publish it quickly. Thank you very, very, very much!

**Comment by ltsfran** [comment]
I had the same error, but my solution was add version property in my private packages "version": "0.0.0" and in my .changeset/config.json
`"ignore": ["docs"]`
In my case my private package was "docs"

**Comment by Pesven-dnv** [comment]
Thanks for the comment @ltsfran, lead me to a solution for us. 

I could not get the ignore to work however, it still wanted the version of my docs project. 
For me it could remain private but it had to have a version number.

Our docs earlier just had * as dependency on internal packages but now it must have the specific pre versions so i kind of understand that it has to modify it now instead of just relying on *. 

Anyway, just adding a version works fine.

**Comment by remorses** [comment]
I opened a very simple PR https://github.com/changesets/changesets/pull/1589 which simply ignores packages without a version

**Comment by Jintus** [comment]
I had the same issue using a pnpm workspace. First I was angry that the PR was not merged but by doing some debugging, particulary where the error throw, I managed to find that the issue was on my side.

The bundler of one of my package add a package.json in a bundled folder. And my `pnpm-workspace.yaml` was too permissive,
`'packages/**'` instead of `'packages/*'`, so changesets identify it as a package.

I found it by adding a console.log in the `changesets-assemble-release-plan.cjs.js` (the file to throw in the error) in the getPreInfo method :

```js
for (const [, pkg] of packagesByName) {
    console.log(pkg.packageJson.name);
    preVersions.set(pkg.packageJson.name, getPreVersion(pkg.packageJson.version));
  }
```

and an unwanted package was logged.

By changing my `pnpm-workspace.yaml` everything worked fine.

**Comment by guesant** [comment]
thank you @Andarist and @remorses 

i can confirm that after upgrading to `@changesets/cli` to `2.29.3` this bug is fixed!

## before the fix - 2.29.2

![Image](https://github.com/user-attachments/assets/3156ddcf-eeb2-488f-bd52-8311fdcb1da0)

## after the fix - 2.29.3

![Image](https://github.com/user-attachments/assets/7cba8373-56e3-4f10-a028-62104dcb94a9)

![Image](https://github.com/user-attachments/assets/f1a6d977-28b5-4188-b9bb-d9784251a7d7)

![Image](https://github.com/user-attachments/assets/bd4cf3c5-4742-4084-a67e-cd3ca4641e47)

![Image](https://github.com/user-attachments/assets/390a497c-c1ff-4c09-b36e-7000c00cd5c7)
