### ISSUE TITLE
Can't find module @changesets/cli/changelog when installed globally

### ISSUE THREAD

**Issue by chris-ldgk** [changesets/changesets#945]
## Affected Packages

@changesets/cli

## Problem

I'm currently trying to use @changesets/cli within a pipeline without needing to install global dependencies to use changelogs.
As such I have @changesets/cli globally installed on the pipeline runner, using npx to run the command.

When using `npx changeset` everything works fine, but using `npx changeset version` throws the following error:

```sh
$ npx changeset version
🦋  error Error: Cannot find module '@changesets/cli/changelog'
🦋  error Require stack:
🦋  error - /myuser/myproject/.changeset/noop.js
🦋  error     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
🦋  error     at resolveFileName (/myuser/.nvm/versions/node/v16.17.0/lib/node_modules/@changesets/cli/node_modules/resolve-from/index.js:29:39)
🦋  error     at resolveFrom (/myuser/.nvm/versions/node/v16.17.0/lib/node_modules/@changesets/cli/node_modules/resolve-from/index.js:43:9)
🦋  error     at Object.module.exports [as default] (/myuser/.nvm/versions/node/v16.17.0/lib/node_modules/@changesets/cli/node_modules/resolve-from/index.js:46:47)
🦋  error     at getNewChangelogEntry (/myuser/.nvm/versions/node/v16.17.0/lib/node_modules/@changesets/cli/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:391:54)
🦋  error     at Object.applyReleasePlan [as default] (/myuser/.nvm/versions/node/v16.17.0/lib/node_modules/@changesets/cli/node_modules/@changesets/apply-release-plan/dist/apply-release-plan.cjs.dev.js:301:37)
🦋  error     at version (/myuser/.nvm/versions/node/v16.17.0/lib/node_modules/@changesets/cli/dist/cli.cjs.dev.js:625:69)
🦋  error     at async run$2 (/myuser/.nvm/versions/node/v16.17.0/lib/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1367:11) {
🦋  error   code: 'MODULE_NOT_FOUND',
🦋  error   requireStack: [
🦋  error     '/myuser/myproject/.changeset/noop.js'
🦋  error   ]
🦋  error }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have looked into my global install of changesets and while changelog is a subdirectory within the package itself, it does not get installed into the packages node_modules, which is how I would explain why it can't actually find the module.

## Minimal reproduction

Navigate into the repository using changesets.

`rm -rf node_modules`
`npm i -g @changesets/cli`
`npx changeset version`

**Comment by Andarist** [comment]
I'm not entirely sure what's the best solution to solve this. I remember @JakeGinnivan was raising this issue in the past. Do you have any ideas how the fix could look like?

**Comment by chris-ldgk** [comment]
I think the easiest way would be to also publish `@changesets/cli/changelog` as a package and then require that within `@changesets/cli`s package.json - that way it would also be installed when install `@changesets/cli` globally and could be resolved.

**Comment by Andarist** [comment]
Oh, I didn't notice at first that this is about `@changesets/cli/changelog`. In such a case, we should be able to resolve this just fine - we just should use relative paths or something there. 

Jake's problem was about `@changesets/changelog-github` and I'm not sure how to make that work. If I understand correctly, each `npx` call should kinda be isolated - so how we'd provide an extra package to its call? Unless you mean something like `npm install -g @changesets/changelog-github && npx changeset version`

**Comment by chris-ldgk** [comment]
The funny thing is that solution also doesn't work. 

Setting `"changelog": "@changesets/changelog-git"` in `.changeset/config.json` and then running `npm i -g @changesets/cli @changesets/changelog-git && npx changeset version` still throws the same error.

**Comment by greatyehanli** [comment]
I encoutered exactly the same issue by forking changeset, modifying the code and trying to run changeset version. It says that the module is not found.

**Comment by greatyehanli** [comment]
Just found the workaround. I found that the changelog path configuration in config json is relative to the directory path of .changeset. If you want to refer to the actual code to see the instant result as you are coding, just give a relative path like { "changelog": "../{rootPathOfMonorepo}/changesets/packages/cli/changelog" }

**Comment by chrisfentiman** [comment]
Thank you, @greatyehanli - I wanted to clarify further the solution you recommended for anyone else who comes across this issue, as I had been scratching my head for 30ish minutes wondering how to solve this.

The key is: 
> You must modify `"changelog"` in your `.changeset/config.json` file to the absolute path of your global node_modules

**Example:**

To use `@changesets/changelog-github` with `npx`:

1. Install `changelog-github` globally `npm i @changesets/changelog-github -g` 
2. Find your global `node_modules` path by running `npm list -g | head -1` 
```bash
# note: I use nvm you may see something different
$ npm list -g | head -1
/Users/{{you}}/.nvm/versions/node/v16.18.0/lib
```
3. Reference the `node_modules` path in your `.changeset/config.json` >> 
```json
{
  "$schema": "https://unpkg.com/@changesets/config@2.2.0/schema.json",
  "changelog": [
    "/Users/{{you}}/.nvm/versions/node/v16.18.0/lib/node_modules/@changesets/changelog-github",
    {
      "repo": "org/repo"
    }
  ]
  ...
}
```

4. Use `npx changeset version` as you expected.

-- 

This is less than ideal, but it works and means I avoid installing a million deps to version the package. 

I can also confirm you can do this with `changeset/action`. However, you will need to create a custom script to complete the steps above and then ensure you clean up by running `git restore .changeset/config.json` before committing to ensure `config.json` is not modified.

**Comment by Netail** [comment]
Facing the same issue when using the changeset/cli in a ci/cd pipeline; `npx changeset version`

**Comment by brense** [comment]
Its not pretty, but we solved this error by adding `@changeset/cli` as a dependency in package.json (**not** dev dependency). Then in the pipeline:
```
npm i @changesets/cli
npx changeset version
```
No idea why this works, but somehow it does.

**Comment by Netail** [comment]
> Its not pretty, but we solved this error by adding `@changeset/cli` as a dependency in package.json (**not** dev dependency). Then in the pipeline:
> 
> ```
> npm i @changesets/cli
> npx changeset version
> ```
> 
> No idea why this works, but somehow it does.

I believe that just installs all dependencies listed in the package.json AND adds @changeset/cli, but with `npx` you should be able to run the CLI but only installing changeset in the home directory

**Comment by Netail** [comment]
A potential fix; https://github.com/changesets/changesets/pull/1500

**Comment by Netail** [comment]
Should be fixed since v2.27.12

**Comment by Andarist** [comment]
closes by https://github.com/changesets/changesets/pull/1562
